version: 0.0.1
language: 'nodejs'
environment_variables:
  - MyVariable # accessible as process.env.MyVariable - value input through the site
methods:
  GET:
    status_codes:
      - 200 # Can only have one 2xx status code and it must be first in the list
      - 400 # Currently accepts 400, 401, 404, 409, 500
      - 401
      - 404
      - 409
      - 500
    path_params:
      - myPathParam : optional # [required or optional], see below for details, accessible as process.env.myPathParam
    query_string_params:
      - myQueryStringParam # accessible as process.env.myQueryStringParam
  POST:
    status_codes:
      - 201 # Can only have one 2xx status code and it must be first in the list
      - 400 # Currently accepts 400, 401, 404, 409, 500
      - 401
      - 404
      - 409
      - 500
    path_params:
      - myPathParam : optional # [required or optional], see below for details, accessible as process.env.myPathParam
    query_string_params:
      - myQueryStringParam # accessible as process.env.myQueryStringParam
  PUT:
    status_codes:
      - 201 # Can only have one 2xx status code and it must be first in the list
      - 400 # Currently accepts 400, 401, 404, 409, 500
      - 401
      - 404
      - 409
      - 500
    path_params:
      - myPathParam : optional # [required or optional], see below for details, accessible as process.env.myPathParam
    query_string_params:
      - myQueryStringParam # accessible as process.env.myQueryStringParam
  DELETE:
    status_codes:
      - 201 # Can only have one 2xx status code and it must be first in the list
      - 400 # Currently accepts 400, 401, 404, 409, 500
      - 401
      - 404
      - 409
      - 500
    path_params:
      - myPathParam : optional # [required or optional], see below for details, accessible as process.env.myPathParam
    query_string_params:
      - myQueryStringParam # accessible as process.env.myQueryStringParam

# path params
# all required must come before optional
# only one optional allowed
